<?php

/**
 * @file
 * Druqs primary module file.
 *
 * TODO add menu item search!
 * TODO add simple extra commands like "run cron", "clear cache"?
 */
use Drupal\Core\Cache\Cache;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_druqs_search().
 */
function druqs_druqs_search($args) {
  $items = array();

  // Get the module config
  $sources = \Drupal::config('druqs.configuration')->get('search_sources');

  // Search for content
  if (in_array('node', $sources)) {
    if ($args['results_current'] < $args['results_max']) {
      // Determine how many results we can still add
      $limit = min($args['results_per_source'], $args['results_max'] - $args['results_current']);
      // Create query for node titles
      $q = \Drupal::database()->select('node_field_data', 'n');
      $q->fields('n', ['nid', 'title', 'type']);
      $q->condition('n.title', '%' . $q->escapeLike($args['input']) . '%', 'LIKE');
      // And format the results
      foreach ($q->range(0, $limit)->execute() as $record) {
        $items[] = array(
          'type' => 'Content (' . Html::escape($record->type) . ')',
          'title' => Html::escape($record->title),
          'actions' => array(
            'view' => '/node/' . $record->nid,
            'edit' => '/node/' . $record->nid . '/edit',
          )
        );
        // Increment the result counter
        $args['results_current']++;
      }
    }
  }

  // Search for users
  if (in_array('user', $sources)) {
    if ($args['results_current'] < $args['results_max']) {
      // Determine how many results we can still add
      $limit = min($args['results_per_source'], $args['results_max'] - $args['results_current']);
      // Create query for node titles
      $q = \Drupal::database()->select('users_field_data', 'u');
      $q->fields('u', ['uid', 'name']);
      $q->condition('u.name', '%' . $q->escapeLike($args['input']) . '%', 'LIKE');
      // And format the results
      foreach ($q->range(0, $limit)->execute() as $record) {
        $items[] = array(
          'type' => 'User',
          'title' => Html::escape($record->name),
          'actions' => array(
            'view' => '/user/' . $record->uid,
            'edit' => '/user/' . $record->uid . '/edit',
          )
        );
        // Increment the result counter
        $args['results_current']++;
      }
    }
  }

  // Search for taxonomy terms
  if (in_array('taxonomy', $sources)) {
    if ($args['results_current'] < $args['results_max']) {
      // Determine how many results we can still add
      $limit = min($args['results_per_source'], $args['results_max'] - $args['results_current']);
      // Create query for node titles
      $q = \Drupal::database()->select('taxonomy_term_field_data', 't');
      $q->fields('t', ['tid', 'name', 'vid']);
      $q->condition('t.name', '%' . $q->escapeLike($args['input']) . '%', 'LIKE');
      // And format the results
      foreach ($q->range(0, $limit)->execute() as $record) {
        $items[] = array(
          'type' => 'Taxonomy (' . Html::escape($record->vid) . ')',
          'title' => Html::escape($record->name),
          'actions' => array(
            'view' => '/taxonomy/term/' . $record->tid,
            'edit' => '/taxonomy/term/' . $record->tid . '/edit',
          )
        );
        // Increment the result counter
        $args['results_current']++;
      }
    }
  }

  return $items;
}

/**
 * Implements hook_help().
 */
function druqs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.druqs':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The druqs module offers an omnipresent search for content and more via the toolbar or a block. By default, it searches nodes and taxonomies, but can easily be extended with a built-in hook.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Search box placement') . '</dt>';
      $output .= '<dd>' . t('By default, the search box is added to the toolbar. Another option is using one of the blocks which ships with the module.') . '</dd>';
      $output .= '<dt>' . t('Search for content') . '</dt>';
      $output .= '<dd>' . t('Start typing in the druqs box to search for nodes by title.') . '</dd>';
      $output .= '<dt>' . t('Search for users') . '</dt>';
      $output .= '<dd>' . t('Start typing in the druqs box to search for users by name.') . '</dd>';
      $output .= '<dt>' . t('Search for taxonomy terms') . '</dt>';
      $output .= '<dd>' . t('Start typing in the druqs box to search for taxonomy terms by name.') . '</dd>';
      $output .= '<dt>' . t('Configuring the module') . '</dt>';
      $output .= '<dd>' . t('You can select which type of content will be searched on <a href=":admin-druqs">the druqs configuration page</a>.', array(':admin-druqs' => Url::fromRoute('druqs.configuration')->toString())) . '</dd>';
      $output .= '<dt>' . t('Permissions') . '</dt>';
      $output .= '<dd>' . t('Users with the <em>Administer druqs</em> permission can configure the module, users with the <em>Access druqs</em> permission can use the druqs.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function druqs_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->hasPermission('access druqs')) {
    $config = \Drupal::config('druqs.configuration');
    $cache_tags = isset($attachments['#cache']['tags']) ? $attachments['#cache']['tags'] : [];
    $attachments['#cache']['tags'] = Cache::mergeTags($cache_tags, $config->getCacheTags());

    $attachments['#attached']['library'][] = 'druqs/drupal.druqs';
    $attachments['#attached']['drupalSettings']['druqs'] = [
      'maxResults' => $config->get('max_results'),
    ];
  }
}

/**
 * Implements hook_hook_info().
 */
function druqs_hook_info() {
  return array(
    'druqs_search' => array(
      'group' => 'druqs',
    ),
  );
}

/**
 * Implements hook_toolbar().
 */
function druqs_toolbar() {
  $items['druqs'] = [
    '#cache' => [
      'contexts' => ['user.permissions'],
    ],
  ];

  // TODO replace the input by a proper drupal form to allow searching without js
  if (\Drupal::currentUser()->hasPermission('access druqs')) {
    $items['druqs'] += [
      '#weight' => -999,
      '#type' => 'toolbar_item',
      'tab' => array(
        '#type' => 'search',
        '#attributes' => array(
          'id' => 'druqs-input',
        ),
        '#suffix' => '<div id="druqs-results"></div>',
      ),
      '#wrapper_attributes' => [
        'class' => ['druqs-tab'],
      ],
      '#attached' => [
        'library' => ['druqs/drupal.druqs'],
      ],
      '#attributes' => [
        'id' => 'druqs',
      ],
    ];
  }

  return $items;
}
