# Schema for the configuration files of the Druqs module.

druqs.configuration:
  type: config_object
  label: 'Druqs settings'
  mapping:
    search_sources:
      type: sequence
      label: 'Search sources'
      sequence:
        - type: string
          label: 'Source'
    results_per_source:
      type: integer
      label: 'Number of items to show in the search results'
